### ISSUE TITLE
Firebase_integration

### ISSUE THREAD

**Issue by jaredtspears** [diloretodg/class_project_1#8]
# Tasks
- [ ] Basic integration Idea - post idea in slack or in github for reference
- [ ] More integration (possibly 2 player score keeping# Tasks) - post idea in slack or in github for reference
- [ ] Difficult integration - post idea in slack or in github for reference

**Comment by diloretodg** [comment]
this is similar to #9

**Comment by jaredtspears** [comment]
issue was not completed.
